Add a new user command to show the secret
alexcoman/arestor pull request #9
Opened 2017-01-05 15:03 UTC by micumatei

2017-01-05 22:37 UTC, alexcoman requested changes

2017-01-05 22:37 UTC, alexcoman commented on arestor/cli/commands/user.py
> +        return self.args.api_key, users.get_secret(api_key=self.args.api_key)
What happens if the `api_key` is not valid ?

2017-01-05 22:37 UTC, alexcoman commented on arestor/cli/commands/user.py
> +        table.add_row([api_key, info])
Why not `add_row(result)` ?

2017-01-05 22:37 UTC, alexcoman commented on arestor/cli/commands/user.py
> +        (_ShowSecret, "actions")
Add a coma.

2017-01-05 23:49 UTC, micumatei commented on arestor/cli/commands/user.py
> +        table.add_row([api_key, info])
Point given :+1: silly mistake

2017-01-09 20:57 UTC, alexcoman requested changes

2017-01-09 20:57 UTC, alexcoman commented on arestor/cli/commands/user.py
> +            return None
I think you should raise an exception (because the information provided by the user is not valid).

2017-01-09 20:57 UTC, alexcoman commented on arestor/cli/commands/user.py
> +            "api_key", help="The client key id.")
Please change with `--api_key` and add the flag `required=True`.
I think the command line `show --api-key xxxx-xxxx-xxxx-xxxx` is more expressive.

2017-01-09 20:57 UTC, alexcoman commented on arestor/cli/commands/user.py
> +            "show", help="Show the secret for a given user.")
I think `show-secret` is more appropriate.

2017-01-10 06:10 UTC, micumatei commented on arestor/cli/commands/user.py
> +            return None
I replicate the openstack projects behaviour, `glance image-list` when nothing to show a blank table is displayed

2017-01-11 20:35 UTC, stefan-caraiman commented on arestor/cli/commands/user.py
> +            return None
Won't there be any unpredictable behaviors by passing a `NoneType` ? From what I understand it seems that it would be best to return an empty string

2017-01-23 09:15 UTC, alexcoman approved these changes

2017-04-10 15:31 UTC, ader1990 commented
closing PR, as it will be done in another one

2017-04-12 17:30 UTC, micumatei commented
This patch is ready and needed.

2017-04-12 17:32 UTC, ader1990 commented
@micumatei please open the PRs on the cloudbase repo

2017-04-12 17:32 UTC, closed without merging